/**
 * @file tpl_app_config.c
 *
 * @section desc File description
 *
 * OS data structure generated from application test
 * Automatically generated by goil on Wed Nov 15 17:48:59 2023
 * from root OIL file lab02.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include <stdbool.h>
#include <stdint.h>

#include "tpl_app_config.h"

#include "tpl_os_internal_types.h"
#include "tpl_machine.h"
#include "tpl_os_interrupt.h"
#include "tpl_os_interrupt_kernel.h"
#include "tpl_os_alarm_kernel.h"
#include "tpl_os_alarm.h"
#include "tpl_os_resource_kernel.h"
#include "tpl_os_resource.h"
#include "tpl_os_event_kernel.h"
#include "tpl_os_event.h"
#include "tpl_os_action.h"
#include "tpl_os_kernel.h"
#include "tpl_os_definitions.h"


#include "tpl_com_notification.h"
#include "tpl_com_mo.h"
#include "tpl_com_internal.h"
#include "tpl_com_internal_com.h"
/*#include "tpl_com_external_com.h"*/
#include "tpl_com_app_copy.h"
#include "tpl_com_filters.h"

/*=============================================================================
 * Application Modes tables for tasks, alarms and schedule tables
 * Application Modes masks are as follow:
 * stdAppmode = 1
 */

CONST(tpl_application_mode, OS_CONST) stdAppmode = 0; /* mask = 1 */
CONST(tpl_application_mode, OS_CONST) OSDEFAULTAPPMODE = 0;
CONST(tpl_appmode_mask, OS_CONST) tpl_task_app_mode[TASK_COUNT] = {
  0 /* task Task_V :  */ ,
  0 /* task Task_M :  */ ,
  1 /* task Periodic_Task_C : stdAppmode */ 
};

CONST(tpl_appmode_mask, OS_CONST) tpl_alarm_app_mode[ALARM_COUNT] = {
  1 /* alarm a100msec : stdAppmode | stdAppmode */ 
};

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of processes IDs
 */

/* Task Task_V identifier */
#define Task_V_id 0
CONST(TaskType, AUTOMATIC) Task_V = Task_V_id;

/* Task Task_M identifier */
#define Task_M_id 1
CONST(TaskType, AUTOMATIC) Task_M = Task_M_id;

/* Task Periodic_Task_C identifier */
#define Periodic_Task_C_id 2
CONST(TaskType, AUTOMATIC) Periodic_Task_C = Periodic_Task_C_id;

/*=============================================================================
 * Declaration of Alarm IDs
 */

/* Alarm a100msec identifier */
#define a100msec_id 0
CONST(AlarmType, AUTOMATIC) a100msec = a100msec_id;

/*=============================================================================
 * Declaration of receive messages IDs
 */

/* Message M_receive identifier */
#define M_receive_id 0
CONST(MessageIdentifier, AUTOMATIC) M_receive = M_receive_id;

/* Message V_receive identifier */
#define V_receive_id 1
CONST(MessageIdentifier, AUTOMATIC) V_receive = V_receive_id;

/*=============================================================================
 * Declaration of send messages IDs
 */

/* Message msgfrom_C identifier */
#define msgfrom_C_id 0
CONST(MessageIdentifier, AUTOMATIC) msgfrom_C = msgfrom_C_id;

/* Message msgfrom_M identifier */
#define msgfrom_M_id 1
CONST(MessageIdentifier, AUTOMATIC) msgfrom_M = msgfrom_M_id;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * The scheduler resource descriptor.
 * One scheduler resource is defined per core.
 *
 * @see #RES_SCHEDULER
 */

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
VAR(tpl_resource, OS_VAR) res_sched_rez_desc = {
  RES_SCHEDULER_PRIORITY,   /*  ceiling priority                            */
  0,                        /*  owner_prev_priority                         */
  INVALID_PROC_ID,          /*  owner                                       */
#if WITH_OSAPPLICATION == YES
  INVALID_OSAPPLICATION_ID, /*  OS Application id                           */
#endif

  NULL                      /*  next_res                                    */
};
#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_resource, AUTOMATIC, OS_APPL_DATA)
tpl_resource_table[RESOURCE_COUNT] = {
  &res_sched_rez_desc
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Definition and initialization of Counters related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Counter SystemCounter descriptor
 */

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_tick, OS_CONST) OSTICKSPERBASE = 1;
CONST(tpl_tick, OS_CONST) OSMAXALLOWEDVALUE = 65535;
CONST(tpl_tick, OS_CONST) OSMINCYCLE = 1;

#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_counter, OS_VAR) SystemCounter_counter_desc = {
  /* ticks per base       */  1,
  /* max allowed value    */  65535,
  /* minimum cycle        */  1,
  /* current tick         */  0,
  /* current date         */  0,
#if WITH_OSAPPLICATION == YES
    /* OS Application id    */  
#endif
    /* first alarm          */  NULL_PTR,
    /* next alarm to raise  */  NULL_PTR
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#include "tpl_os_kernel.h"          /* tpl_schedule */
#include "tpl_os_timeobj_kernel.h"  /* tpl_counter_tick */
#include "tpl_machine_interface.h"  /* tpl_switch_context_from_it */

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

//gcc uses ISR as a keyword to define an interrupt handler.
//Osek uses ISR to define an ISR2 :-/
#ifdef ISR
 #undef ISR
#endif
#include <avr/interrupt.h>

//function defined in avr assembly files.
FUNC(void, OS_CODE) tpl_avr_counter_tick(
    P2VAR(tpl_counter, AUTOMATIC, OS_APPL_DATA) counter);


void trampolineSystemCounter()
{
  tpl_avr_counter_tick(&SystemCounter_counter_desc);
}
  
#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Descriptor(s) of the idle task(s)
 */
/*-----------------------------------------------------------------------------
 * Task IDLE_TASK descriptor
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"
/*
 * Task IDLE_TASK function prototype
 */

FUNC(void, OS_APPL_CODE) idle_function(void);
#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */

/*
 * Task IDLE_TASK stack
 *
 */
#define APP_Task_IDLE_TASK_START_SEC_STACK
#include "tpl_memmap.h"
tpl_stack_word IDLE_TASK_stack_zone[IDLE_STACK_SIZE/sizeof(tpl_stack_word)];
#define APP_Task_IDLE_TASK_STOP_SEC_STACK
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define IDLE_TASK_STACK { IDLE_TASK_stack_zone, IDLE_STACK_SIZE }

/*
 * Task IDLE_TASK context
 */
avr_context IDLE_TASK_int_context;
#define IDLE_TASK_CONTEXT &IDLE_TASK_int_context

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task IDLE_TASK
 */
CONST(tpl_proc_static, OS_CONST) IDLE_TASK_task_stat_desc = {
  /* context                  */  IDLE_TASK_CONTEXT,
  /* stack                    */  IDLE_TASK_STACK,
  /* entry point (function)   */  idle_function,
  /* internal ressource       */  NULL,
  /* task id                  */  IDLE_TASK_ID,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  0,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task IDLE_TASK
 */
VAR(tpl_proc, OS_VAR) IDLE_TASK_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  0,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Task related defines and structures
 */
/*-----------------------------------------------------------------------------
 * Task Task_V descriptor
 */
#define APP_Task_Task_V_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task Task_V function prototype
 */

FUNC(void, OS_APPL_CODE) Task_V_function(void);
#define APP_Task_Task_V_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */

/*
 * Task Task_V stack
 *
 */
#define APP_Task_Task_V_START_SEC_STACK
#include "tpl_memmap.h"
tpl_stack_word Task_V_stack_zone[8192/sizeof(tpl_stack_word)];
#define APP_Task_Task_V_STOP_SEC_STACK
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define Task_V_STACK { Task_V_stack_zone, 8192 }

/*
 * Task Task_V context
 */
avr_context Task_V_int_context;
#define Task_V_CONTEXT &Task_V_int_context

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task Task_V
 */
CONST(tpl_proc_static, OS_CONST) Task_V_task_stat_desc = {
  /* context                  */  Task_V_CONTEXT,
  /* stack                    */  Task_V_STACK,
  /* entry point (function)   */  Task_V_function,
  /* internal ressource       */  NULL,
  /* task id                  */  Task_V_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  1,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task Task_V
 */
VAR(tpl_proc, OS_VAR) Task_V_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  1,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task Task_M descriptor
 */
#define APP_Task_Task_M_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task Task_M function prototype
 */

FUNC(void, OS_APPL_CODE) Task_M_function(void);
#define APP_Task_Task_M_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */

/*
 * Task Task_M stack
 *
 */
#define APP_Task_Task_M_START_SEC_STACK
#include "tpl_memmap.h"
tpl_stack_word Task_M_stack_zone[8192/sizeof(tpl_stack_word)];
#define APP_Task_Task_M_STOP_SEC_STACK
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define Task_M_STACK { Task_M_stack_zone, 8192 }

/*
 * Task Task_M context
 */
avr_context Task_M_int_context;
#define Task_M_CONTEXT &Task_M_int_context

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task Task_M
 */
CONST(tpl_proc_static, OS_CONST) Task_M_task_stat_desc = {
  /* context                  */  Task_M_CONTEXT,
  /* stack                    */  Task_M_STACK,
  /* entry point (function)   */  Task_M_function,
  /* internal ressource       */  NULL,
  /* task id                  */  Task_M_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  2,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task Task_M
 */
VAR(tpl_proc, OS_VAR) Task_M_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  2,
  /* task state                     */  SUSPENDED
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Task Periodic_Task_C descriptor
 */
#define APP_Task_Periodic_Task_C_START_SEC_CODE

#include "tpl_memmap.h"
/*
 * Task Periodic_Task_C function prototype
 */

FUNC(void, OS_APPL_CODE) Periodic_Task_C_function(void);
#define APP_Task_Periodic_Task_C_STOP_SEC_CODE

#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Target specific structures
 */

/*
 * Task Periodic_Task_C stack
 *
 */
#define APP_Task_Periodic_Task_C_START_SEC_STACK
#include "tpl_memmap.h"
tpl_stack_word Periodic_Task_C_stack_zone[8192/sizeof(tpl_stack_word)];
#define APP_Task_Periodic_Task_C_STOP_SEC_STACK
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define Periodic_Task_C_STACK { Periodic_Task_C_stack_zone, 8192 }

/*
 * Task Periodic_Task_C context
 */
avr_context Periodic_Task_C_int_context;
#define Periodic_Task_C_CONTEXT &Periodic_Task_C_int_context

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"




/*
  No timing protection
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*
 * Static descriptor of task Periodic_Task_C
 */
CONST(tpl_proc_static, OS_CONST) Periodic_Task_C_task_stat_desc = {
  /* context                  */  Periodic_Task_C_CONTEXT,
  /* stack                    */  Periodic_Task_C_STACK,
  /* entry point (function)   */  Periodic_Task_C_function,
  /* internal ressource       */  NULL,
  /* task id                  */  Periodic_Task_C_id,
#if WITH_OSAPPLICATION == YES
  /* OS application id        */  
#endif
  /* task base priority       */  3,
  /* max activation count     */  1,
  /* task type                */  TASK_BASIC,
#if WITH_AUTOSAR_TIMING_PROTECTION == YES

  /* execution budget */        0,
  /* timeframe        */        0, 
  /* pointer to the timing
     protection descriptor    */ NULL

#endif
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"
/*
 * Dynamic descriptor of task Periodic_Task_C
 */
VAR(tpl_proc, OS_VAR) Periodic_Task_C_task_desc = {
  /* resources                      */  NULL,
#if WITH_OSAPPLICATION == YES
  /* if > 0 the process is trusted  */  0,    
#endif /* WITH_OSAPPLICATION */
  /* activate count                 */  0,
  /* task priority                  */  3,
  /* task state                     */  AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#include "tpl_machine.h"
#define OS_START_SEC_CODE
#include "tpl_memmap.h"

//function defined in avr assembly files.
FUNC(void, OS_CODE) tpl_avr_ISR2_handler(CONST(uint16, AUTOMATIC) id);


#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*=============================================================================
 * Definition and initialization of process tables (tasks and isrs)
 */
CONSTP2CONST(tpl_proc_static, AUTOMATIC, OS_APPL_DATA)
tpl_stat_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &Task_V_task_stat_desc,
  &Task_M_task_stat_desc,
  &Periodic_Task_C_task_stat_desc,
  &IDLE_TASK_task_stat_desc
};

CONSTP2VAR(tpl_proc, AUTOMATIC, OS_APPL_DATA)
tpl_dyn_proc_table[TASK_COUNT+ISR_COUNT+1] = {
  &Task_V_task_desc,
  &Task_M_task_desc,
  &Periodic_Task_C_task_desc,
  &IDLE_TASK_task_desc
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of Alarm related structures
 */
/*-----------------------------------------------------------------------------
 * Alarm a100msec descriptor
 *
 * This alarm does the activation of task Task_M
 */


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_task_activation_action, OS_CONST) a100msec_action = {
  {
    /* action function  */  tpl_action_activate_task
  },
  /* task id            */  Task_M_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
 
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_alarm_static, OS_CONST) a100msec_static = {
  {
    /* pointer to counter           */  &SystemCounter_counter_desc,
    /* pointer to the expiration    */  tpl_raise_alarm
#if (WITH_ID == YES)
    /* id of the alarm for tracing  */  , a100msec_id
#endif
#if WITH_OSAPPLICATION == YES
    /* OS application id            */  , 
#endif
  },
  /* action of the alarm  */  (tpl_action *)&a100msec_action
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_time_obj, OS_VAR) a100msec_alarm_desc = {
    /* pointer to the static part   */  (tpl_time_obj_static *)&a100msec_static,
    /* next alarm                   */  NULL,
    /* prev alarm                   */  NULL,
    /* cycle                        */  500,
    /* date                         */  500,
    /* State of the alarm           */  ALARM_AUTOSTART
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"


#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2VAR(tpl_time_obj, AUTOMATIC, OS_APPL_DATA)
  tpl_alarm_table[ALARM_COUNT] = {
  &a100msec_alarm_desc
};
#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Declaration of flags functions
 */
/* $FLAGSFUNCTIONS$ */


/*=============================================================================
 * Definition and initialization of Receive Messages related structures
 */

/*-----------------------------------------------------------------------------
 * Action of message M_receive
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_task_activation_action, OS_CONST) M_receive_action = {
  {
    /* action function  */  tpl_action_activate_task
  },
  /* task id            */  Task_M_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*-----------------------------------------------------------------------------
 * ALWAYS filter of message object M_receive
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

tpl_noparam_filter_desc M_receive_filter = {
    /*  filtering function          */  tpl_filter_always
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Static internal receiving queued message object M_receive
 */
 
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(int, OS_VAR) M_receive_buffer[10];
VAR(int, OS_VAR) M_receive_last;

VAR(tpl_queue_dyn, OS_VAR) M_receive_dyn_queue = {
  /*  current size of the queue           */  0,
  /*  read index                          */  0,
  /*  overflow flag                       */  FALSE
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_internal_receiving_queued_mo, OS_CONST) M_receive_message = {
  { /* data receiving mo struct   */
    { /* base receiving mo struct */
      /* notification pointer     */  (tpl_action *)&M_receive_action,
      /* next receiving mo        */  NULL
    },
    /*  receiving function      */  (tpl_receiving_func)tpl_receive_static_internal_queued_message,
    /*  copy function           */  (tpl_data_copy_func)tpl_copy_from_queued,
    /*  filter pointer          */  (tpl_filter_desc *)&M_receive_filter
  },
  { /*  queue structure   */
    /*  pointer to the dynamic descriptor   */  &M_receive_dyn_queue,
    /*  max size of the queue               */  10*sizeof(int),
    /*  element size of the queue           */  sizeof(int),
    /*  pointer to the buffer               */  (tpl_com_data *)M_receive_buffer,
    /*  pointer to the last written value   */  (tpl_com_data *)&M_receive_last
  }
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Action of message V_receive
 */

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_task_activation_action, OS_CONST) V_receive_action = {
  {
    /* action function  */  tpl_action_activate_task
  },
  /* task id            */  Task_V_id
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*-----------------------------------------------------------------------------
 * ALWAYS filter of message object V_receive
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

tpl_noparam_filter_desc V_receive_filter = {
    /*  filtering function          */  tpl_filter_always
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Static internal receiving queued message object V_receive
 */
 
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(int, OS_VAR) V_receive_buffer[15];
VAR(int, OS_VAR) V_receive_last;

VAR(tpl_queue_dyn, OS_VAR) V_receive_dyn_queue = {
  /*  current size of the queue           */  0,
  /*  read index                          */  0,
  /*  overflow flag                       */  FALSE
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_internal_receiving_queued_mo, OS_CONST) V_receive_message = {
  { /* data receiving mo struct   */
    { /* base receiving mo struct */
      /* notification pointer     */  (tpl_action *)&V_receive_action,
      /* next receiving mo        */  NULL
    },
    /*  receiving function      */  (tpl_receiving_func)tpl_receive_static_internal_queued_message,
    /*  copy function           */  (tpl_data_copy_func)tpl_copy_from_queued,
    /*  filter pointer          */  (tpl_filter_desc *)&V_receive_filter
  },
  { /*  queue structure   */
    /*  pointer to the dynamic descriptor   */  &V_receive_dyn_queue,
    /*  max size of the queue               */  15*sizeof(int),
    /*  element size of the queue           */  sizeof(int),
    /*  pointer to the buffer               */  (tpl_com_data *)V_receive_buffer,
    /*  pointer to the last written value   */  (tpl_com_data *)&V_receive_last
  }
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Definition and initialization of the receive messages table
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONSTP2CONST(tpl_base_receiving_mo, AUTOMATIC, OS_CONST)
tpl_receive_message_table[RECEIVE_MESSAGE_COUNT] = {
  (tpl_base_receiving_mo*)&M_receive_message,    
  (tpl_base_receiving_mo*)&V_receive_message
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*=============================================================================
 * Definition and initialization of Send Messages related structures
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Static internal sending static message object msgfrom_C
 */
CONST(tpl_internal_sending_mo, OS_CONST) msgfrom_C_message = {
  { /* base message object       */
    /* sending function          */ tpl_send_static_internal_message
  },
  /* pointer to the receiving mo */ (tpl_base_receiving_mo *)&M_receive_message
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

/*-----------------------------------------------------------------------------
 * Static internal sending static message object msgfrom_M
 */
CONST(tpl_internal_sending_mo, OS_CONST) msgfrom_M_message = {
  { /* base message object       */
    /* sending function          */ tpl_send_static_internal_message
  },
  /* pointer to the receiving mo */ (tpl_base_receiving_mo *)&V_receive_message
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/*=============================================================================
 * Definition and initialization of the send messages table
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONSTP2CONST(tpl_base_sending_mo, AUTOMATIC, OS_CONST)
tpl_send_message_table[SEND_MESSAGE_COUNT] = {
  (tpl_base_sending_mo*)&msgfrom_C_message,    
  (tpl_base_sending_mo*)&msgfrom_M_message
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
/*=============================================================================
 * Definition and initialization of Ready List structures
 */
#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

VAR(tpl_heap_entry, OS_VAR) tpl_ready_list[5];
VAR(tpl_rank_count, OS_VAR) tpl_tail_for_prio[5] = {
  0,
  0,
  0,
  0
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

/**
 * @internal
 *
 * tpl_kern gather informations on the current executing object and
 * the previous one
 */
VAR(tpl_kern_state, OS_VAR) tpl_kern =
{
  NULL,                      /* no running task static descriptor   */
  &IDLE_TASK_task_stat_desc, /* elected task to run is idle task    */
  NULL,                      /* no running task dynamic descriptor  */
  &IDLE_TASK_task_desc,      /* elected task to run is idle task    */
  INVALID_PROC_ID,           /* no running task so no ID            */
  INVALID_PROC_ID,           /* idle task has no ID                 */
  NO_NEED_SWITCH,            /* no context switch needed at start   */
  FALSE,                     /* no schedule needed at start         */
#if WITH_MEMORY_PROTECTION == YES
  1,                         /* at early system startup, we run in  */
                             /*  kernel mode, so in trusted mode    */
#endif /* WITH_MEMORY_PROTECTION */
};

#define OS_STOP_SEC_VAR_UNSPECIFIED
#include "tpl_memmap.h"

#define API_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"
CONSTP2CONST(char, AUTOMATIC, OS_APPL_DATA) proc_name_table[TASK_COUNT + ISR_COUNT + 1] = {

  "Task_V",
  "Task_M",
  "Periodic_Task_C",
  "*idle*"
};
#define API_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"


/* End of file tpl_app_config.c */
